### ISSUE TITLE
Read the Docs: broken image links

### ISSUE THREAD

**Issue by thocevar** [biolab/orange3-educational#118]
https://orange3-educational.readthedocs.io/en/latest/widgets/interactive-kmeans.html#example

**Comment by ajdapretnar** [comment]
I think it is an issue of Read the Docs, because the paths are correct and the documentation gets built just fine with sphinx.

**Comment by ajdapretnar** [comment]
On the other hand, it could be [this incompatibility](https://github.com/sphinx-doc/sphinx/issues/3800) with recommonmark and Sphinx. But I have updated both and the documents seem to generate fine with `make html`/`make htmlhelp`. 🤔

**Comment by PrimozGodec** [comment]
Before https://github.com/biolab/orange3-educational/pull/109 it was also the issue while building offline since the parser for markdown was not set correctly. 

It seems that readthedocs have some issues with parsing new updates since the documentation at read the docs is still old.

**Comment by PrimozGodec** [comment]
It should be working for latest now https://orange3-educational.readthedocs.io/en/latest/
Stable would be fixed after the release. :)
