### ISSUE TITLE
Google Sheets: can't read anything

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-educational#130]
##### Educational version

0.5.0

##### Orange version

3.30.2dev

##### Expected behavior
Google Sheets loads file from the link.

##### Actual behavior
Google Sheets (and also File) say they can't read the data from the URL.

##### Steps to reproduce the behavior
Try to load any sheet with Google Sheets.

##### Additional info (worksheets, data, screenshots, ...)
/

**Comment by fabform** [comment]
Handy to [find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by janezd** [comment]
@ajdapretnar, this has been fixed, right? It works for me.

**Comment by ajdapretnar** [comment]
I believe it was fixed in https://github.com/biolab/orange3/pull/5788/files.
