### ISSUE TITLE
Replace "Variance" in Random Data Widget (Normal Distribution) with "Standard Deviation"

### ISSUE THREAD

**Issue by EKal-aa** [biolab/orange3-educational#137]
##### Educational version
0.5.0

##### Orange version
3.31.1

##### Expected behavior
Using Random Data Widget to produce sample data with normal distribution, the number in the field called "Variance" should be the variance in the sampled data. Or, the name of the field should be "Standard Deviation".

![grafik](https://user-images.githubusercontent.com/55889795/152640781-42d19b37-e3ae-46cd-9774-88fb74387288.png)

##### Actual behavior
The field is called "Variance", but the number works as standard deviation.

Codesnipped of owrandomdata.py
![grafik](https://user-images.githubusercontent.com/55889795/152640860-c23bef6f-0677-4436-9b8c-9ebd77f51143.png)

Part of Documentation of scipy.stats.norm
![grafik](https://user-images.githubusercontent.com/55889795/152640877-eb0d914c-01df-4a6f-81ca-88890f9afe16.png)

##### Steps to reproduce the behavior
- Produce some variables with the radom data widget, for example one uniform distibution as x and one normal distibution as epsilon. 
- Use Feature Constructor to create a target variable out of the data including an additive part of epsilon. 
- Select Columns, so that epsilon is ignored and no longer in the data.
- train a model and use Test and Score, cross validation to test the model.
- The variance of epsilon should correspond to MSE in Test and Score, the standard deviation should correspond to RMSE.

##### Additional info (worksheets, data, screenshots, ...)
![grafik](https://user-images.githubusercontent.com/55889795/152641198-943e5dbe-c3c0-4fd6-8d6d-b2a8369592d4.png)
[random_data_widget.zip](https://github.com/biolab/orange3-educational/files/8007970/random_data_widget.zip)

**Comment by janezd** [comment]
Fixed. Thank you for reporting this!
