### ISSUE TITLE
Make it clear that the EnKlik Anketa widget requires a paid account

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3-educational#152]
From the information on the types of accounts on the 1ka website, it isn't very clear that a paid account is needed to use the functionality that the EnKlik Anketa widget requires for input. Perhaps this was different at the time the widget was created. To avoid disappointment, I suggest to mention the need for a paid account in the dialog box or the help page.
In addition, the "Learn more" link in the dialog box and the link to Enklik Anketa (English website) on the help page don't work

**Comment by janezd** [comment]
We decided to remove it.
