### ISSUE TITLE
Polynomial univariate regression

### ISSUE THREAD

**Issue by janezd** [biolab/orange3-educational#20]
During lectures we noticed that the widget should have an indicator that it uses a regressor from the input. Perhaps also show some additional information (at least a name).

**Comment by BlazZupan** [comment]
It would be handy to add an info box that displays RMSE of the currently fitted model. And an option to plot error bars (a vertical line from each point to the prediction line).

**Comment by PrimozGodec** [comment]
It is good idea. I can implement it next week.

**Comment by ajdapretnar** [comment]
> Perhaps also show some additional information (at least a name).

Should probably be included in report as well.

**Comment by PrimozGodec** [comment]
via

**Comment by PrimozGodec** [comment]
Closed via https://github.com/biolab/orange3-educational/pull/22
